import type { RareEventEntry } from "../types.js";

/**
 * v1 restricted library (~15-20 per 09_IMPLEMENTATION_PLAN.md Phase 8).
 * Every entry is cosmetic only (07_META_GAME.md §6: "aucun impact sur les
 * règles officielles du jeu") — never reference these keys from any
 * scoring or rules code.
 */
export const RARE_EVENTS: RareEventEntry[] = [
  {
    key: "vache_astronaute",
    name: "Vache astronaute",
    flavorText: "Une vache devient astronaute et s'envole vers les étoiles !",
    vfx: "confetti-launch",
    sound: "whoosh",
    weight: 1,
  },
  {
    key: "pluie_de_billets",
    name: "Pluie de billets",
    flavorText: "Il pleut des billets sur la ferme !",
    vfx: "money-rain",
    sound: "cha-ching-soft",
    weight: 1,
  },
  {
    key: "tracteur_abime_carte",
    name: "Tracteur farceur",
    flavorText: "Le tracteur a laissé une trace de boue sur une carte (purement cosmétique).",
    vfx: "mud-splash",
    sound: "engine-sputter",
    weight: 1,
  },
  {
    key: "poule_surprise",
    name: "Poule surprise",
    flavorText: "Une poule surprise s'invite dans l'enchère !",
    vfx: "feather-burst",
    sound: "cluck",
    weight: 1,
  },
  {
    key: "jackpot_ferme",
    name: "Jackpot de ferme",
    flavorText: "Jackpot de ferme ! (sans effet sur le score, promis)",
    vfx: "gold-sparkle",
    sound: "fanfare-short",
    weight: 1,
  },
  {
    key: "eclipse_ferme",
    name: "Éclipse sur la ferme",
    flavorText: "Une éclipse plonge la ferme dans une lumière étrange.",
    vfx: "screen-dim-pulse",
    sound: "eerie-hum",
    weight: 1,
  },
  {
    key: "arc_en_ciel",
    name: "Arc-en-ciel",
    flavorText: "Un arc-en-ciel apparaît au-dessus de la grange.",
    vfx: "rainbow-arc",
    sound: "chime-glimmer",
    weight: 1,
  },
  {
    key: "ovni_survole",
    name: "OVNI en approche",
    flavorText: "Un OVNI survole discrètement le champ...",
    vfx: "ufo-flyby",
    sound: "sci-fi-blip",
    weight: 1,
  },
  {
    key: "canard_deguise",
    name: "Canard déguisé",
    flavorText: "Un canard déguisé en vache tente de se faufiler dans le troupeau.",
    vfx: "disguise-wobble",
    sound: "quack-muffled",
    weight: 1,
  },
  {
    key: "tempete_de_plumes",
    name: "Tempête de plumes",
    flavorText: "Une tempête de plumes traverse la cour de la ferme.",
    vfx: "feather-storm",
    sound: "wind-gust",
    weight: 1,
  },
  {
    key: "fanfare_villageoise",
    name: "Fanfare villageoise",
    flavorText: "La fanfare du village débarque sans prévenir !",
    vfx: "confetti-launch",
    sound: "brass-fanfare",
    weight: 1,
  },
  {
    key: "cochon_danseur",
    name: "Cochon danseur",
    flavorText: "Un cochon danseur improvise un numéro de claquettes.",
    vfx: "dance-wiggle",
    sound: "tap-shoes",
    weight: 1,
  },
  {
    key: "vent_de_folie",
    name: "Vent de folie",
    flavorText: "Un vent de folie souffle sur les enchères, les chapeaux s'envolent !",
    vfx: "wind-swirl",
    sound: "wind-gust",
    weight: 1,
  },
  {
    key: "lune_de_foin",
    name: "Pleine lune sur les meules de foin",
    flavorText: "Une pleine lune éclaire étrangement les meules de foin.",
    vfx: "moonlight-glow",
    sound: "eerie-hum",
    weight: 1,
  },
  {
    key: "sosie_fermier",
    name: "Le sosie du fermier",
    flavorText: "Le sosie du fermier débarque et personne ne sait qui est qui.",
    vfx: "double-vision",
    sound: "comedic-horn",
    weight: 1,
  },
  {
    key: "mouton_zen",
    name: "Mouton zen",
    flavorText: "Un mouton médite paisiblement au milieu du champ.",
    vfx: "zen-shimmer",
    sound: "chime-glimmer",
    weight: 1,
  },
  {
    key: "record_du_village",
    name: "Nouveau record du village",
    flavorText: "Nouveau record du village ! (aucune conséquence sur ton score)",
    vfx: "gold-sparkle",
    sound: "fanfare-short",
    weight: 1,
  },
  {
    key: "etoile_filante",
    name: "Étoile filante",
    flavorText: "Une étoile filante traverse le ciel au-dessus de la ferme.",
    vfx: "shooting-star",
    sound: "chime-glimmer",
    weight: 1,
  },
];
